name: Github Actions Demo
on:
  push:
    branches:
      - main
    paths-ignore:
      - './github/**'
  pull_request:
    branches:
      - main
  schedule:
    - cron: "15 6 * * 0"
  workflow_dispatch:
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: output event
        run: 'echo "event: ${{ github.event_name }}"'
      - name: output branch
        run: 'echo "branch: ${{ github.ref }}"'
      - uses: actions/checkout@v3.3.0
      - name: list files
        run: tree
